# Generated by Django 4.0.3 on 2022-03-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=20)),
                ('marks', models.IntegerField()),
                ('pass_date', models.DateField(max_length=20)),
            ],
        ),
    ]
