# Generated by Django 4.0.3 on 2022-03-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0002_rename_marks_student_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('emp', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('join_date', models.DateField(max_length=20)),
            ],
        ),
    ]
