# Generated by Django 4.0.3 on 2022-03-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0005_student1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student1',
            name='adddatetime',
            field=models.DateTimeField(max_length=20),
        ),
    ]
